import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const CONFIG_REFERENCE_MDX_URL =
  "https://raw.githubusercontent.com/ghostty-org/website/refs/heads/main/docs/config/reference.mdx";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const generatedPath = path.join(root, "src/lib/generated/config-keys.ts");
const grammarPath = path.join(root, "syntaxes/ghostty-config.tmLanguage.json");
const schemaPath = path.join(root, "src/lib/schema.ts");

type Entry = { key: string; desc: string };

async function fetchMdx(): Promise<string> {
  const res = await fetch(CONFIG_REFERENCE_MDX_URL);
  if (!res.ok) {
    throw new Error(`Failed to fetch MDX: ${res.status} ${res.statusText}`);
  }
  return res.text();
}

function stripInlineJsx(text: string): string {
  return text
    .replace(/<\/?[A-Z][A-Za-z0-9]*(?:\s[^>]*)?>/g, "")
    .replace(/\s{2,}/g, " ")
    .trim();
}

function extractDesc(body: string): string {
  for (const raw of body.split(/\n\s*\n/)) {
    const block = raw.trim();
    if (!block) continue;
    if (block.startsWith("```")) continue;
    if (block.startsWith("import ")) continue;
    if (/^<[A-Z]/.test(block)) continue;
    return stripInlineJsx(block.replace(/\s*\n\s*/g, " "))
      .replace(/\s*(?:for example|for instance|e\.g\.)\s*:\s*$/i, "")
      .trim();
  }
  return "";
}

function parseEntries(mdx: string): Entry[] {
  const headingRe = /^## `([^`]+)`\s*$/gm;
  const matches = [...mdx.matchAll(headingRe)];
  const entries: Entry[] = [];

  for (let i = 0; i < matches.length; i++) {
    const key = matches[i][1];
    const start = (matches[i].index ?? 0) + matches[i][0].length;
    const end =
      i + 1 < matches.length
        ? (matches[i + 1].index ?? mdx.length)
        : mdx.length;

    let body = mdx.slice(start, end);
    const nextHeading = body.search(/\n#{1,2} /);
    if (nextHeading !== -1) body = body.slice(0, nextHeading);

    entries.push({ key, desc: extractDesc(body) });
  }

  // Grouped headings stack consecutively and share one description placed under
  // the last heading in the group, leaving the earlier keys with empty bodies.
  for (let i = entries.length - 1; i >= 0; i--) {
    if (entries[i].desc === "" && i + 1 < entries.length) {
      entries[i].desc = entries[i + 1].desc;
    }
  }

  return entries;
}

function writeConfigKeys(entries: Entry[]): void {
  const header = [
    "// AUTO-GENERATED by `pnpm gen:config`. Do not edit by hand.",
    `// Source: ${CONFIG_REFERENCE_MDX_URL}`,
    "",
    "export type GeneratedConfigKey = { key: string; desc: string };",
    "",
    "export const configKeys = [",
  ].join("\n");

  const body = entries
    .map(
      (e) =>
        `  { key: ${JSON.stringify(e.key)}, desc: ${JSON.stringify(e.desc)} },`,
    )
    .join("\n");

  mkdirSync(path.dirname(generatedPath), { recursive: true });
  writeFileSync(
    generatedPath,
    `${header}\n${body}\n] as const satisfies readonly GeneratedConfigKey[];\n`,
  );
}

async function collectEnumValues(): Promise<string[]> {
  const { ghosttyConfigOptions } = (await import(
    pathToFileURL(schemaPath).href
  )) as typeof import("../src/lib/schema");

  return [...new Set(ghosttyConfigOptions.flatMap((o) => o.enum ?? []))]
    .map(String)
    .sort((a, b) =>
      a.length === b.length ? a.localeCompare(b) : b.length - a.length,
    );
}

function updateGrammar(keys: string[], enumValues: string[]): void {
  const grammar = JSON.parse(readFileSync(grammarPath, "utf8"));
  grammar.repository.assignment.patterns[0].begin = `^(\\s*)(${keys.join("|")})(\\s*)(=)(\\s*)`;
  const enumGroup = `(?:${enumValues.join("|")})`;
  const enumTail = `(?=\\s*(?:,|$))`;
  grammar.repository.enum.patterns[0].match = `\\G${enumGroup}${enumTail}`;
  grammar.repository.enum.patterns[1].match = `(,)(\\s*)(${enumGroup})${enumTail}`;
  writeFileSync(grammarPath, `${JSON.stringify(grammar, null, 2)}\n`);
}

async function main(): Promise<void> {
  const mdx = await fetchMdx();
  const entries = parseEntries(mdx);
  if (entries.length === 0) throw new Error("No config keys parsed from MDX");

  writeConfigKeys(entries);
  const enumValues = await collectEnumValues();
  updateGrammar(
    entries.map((e) => e.key),
    enumValues,
  );

  console.log(
    `Generated ${entries.length} keys → config-keys.ts and grammar (${enumValues.length} enum values).`,
  );
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
